// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEQyw4hA9PTaXRt38bGcHvbVbfngWAsvo',
    appId: '1:1010107860692:web:405717b8f88e216cc69d41',
    messagingSenderId: '1010107860692',
    projectId: 'messageboardapp-65a25',
    authDomain: 'messageboardapp-65a25.firebaseapp.com',
    storageBucket: 'messageboardapp-65a25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQseG_LwxyJgNbcWarL6znEJ2p_emQ_7Y',
    appId: '1:1010107860692:android:de9b6876cd2ba071c69d41',
    messagingSenderId: '1010107860692',
    projectId: 'messageboardapp-65a25',
    storageBucket: 'messageboardapp-65a25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWGJhDizHBhgDc_qjixvKixq7EWjkhA7Q',
    appId: '1:1010107860692:ios:70622ef7c314d56bc69d41',
    messagingSenderId: '1010107860692',
    projectId: 'messageboardapp-65a25',
    storageBucket: 'messageboardapp-65a25.firebasestorage.app',
    iosBundleId: 'com.example.messageboardapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWGJhDizHBhgDc_qjixvKixq7EWjkhA7Q',
    appId: '1:1010107860692:ios:70622ef7c314d56bc69d41',
    messagingSenderId: '1010107860692',
    projectId: 'messageboardapp-65a25',
    storageBucket: 'messageboardapp-65a25.firebasestorage.app',
    iosBundleId: 'com.example.messageboardapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEQyw4hA9PTaXRt38bGcHvbVbfngWAsvo',
    appId: '1:1010107860692:web:4ea290c9d71a1e77c69d41',
    messagingSenderId: '1010107860692',
    projectId: 'messageboardapp-65a25',
    authDomain: 'messageboardapp-65a25.firebaseapp.com',
    storageBucket: 'messageboardapp-65a25.firebasestorage.app',
  );
}
